export const progress = [
  {
    stage: "Pending Pickup",
    description: "Pickup requested; staff on the way.",
    status_date: null,
    completed: true,
    falseDescription: "Pickup request received; waiting for staff assignment.",
  },
  {
    stage: "Ongoing Pickup",
    description: "Pickup in progress.",
    status_date: null,
    completed: false,
    falseDescription: "Pickup has not yet started.",
  },
  {
    stage: "Completed Pickup",
    description: "Pickup completed successfully.",
    status_date: null,
    completed: false,
    falseDescription: "Pickup has not been completed.",
  },
  {
    stage: "At Store",
    description: "Dropped off at the laundry store.",
    status_date: null,
    completed: false,
    falseDescription: "The clothes have not yet arrived at the store.",
  },
  {
    stage: "In Queue",
    description: "Waiting for processing.",
    status_date: null,
    completed: false,
    falseDescription: "Not yet in queue for processing.",
  },
  {
    stage: "In Laundry",
    description: "Currently being washed/dried.",
    status_date: null,
    completed: false,
    falseDescription: "Laundry has not started processing yet.",
  },
  {
    stage: "Laundry Completed",
    description: "Washing/drying finished.",
    status_date: null,
    completed: false,
    falseDescription: "Laundry processing has not been completed.",
  },
  {
    stage: "Ready for Delivery",
    description: "Ready to be delivered.",
    status_date: null,
    completed: false,
    falseDescription: "Laundry is not yet ready for delivery.",
  },
  {
    stage: "Out for Delivery",
    description: "On the way to you.",
    status_date: null,
    completed: false,
    falseDescription: "Laundry has not been dispatched yet.",
  },
  {
    stage: "Completed Delivery",
    description: "Delivered and payment confirmed.",
    status_date: null,
    completed: false,
    falseDescription: "Delivery has not been completed.",
  },
];
