// [
//   {
//     success: true,
//     data: [
//       {
//         id: 8,
//         store_id: 1,
//         user_id: 3,
//         customer_id: 2,
//         tracking_code: "#4CD7975DFD894FFCB217",
//         customer_fullname: "John Reynald P Velarde",
//         customer_type: "Online",
//         delivery_date: null,
//         notes: null,
//         payment_method: "Cash on Delivery",
//         pickup_date: null,
//         queue_number: null,
//         request_date: "2024-11-03T09:52:18.000Z",
//         request_status: "Completed Pickup",
//         service_name: "Wash",
//         service_type_id: 1,
//       },
//     ],
//   },
// ];

export const sampleData = [
  {
    id: 8,
    store_id: 1,
    user_id: 3,
    customer_id: 2,
    tracking_code: "#4CD7975DFD894FFCB217",
    customer_fullname: "John Reynald P Velarde",
    customer_type: "Online",
    delivery_date: null,
    notes: null,
    payment_method: "Cash on Delivery",
    pickup_date: null,
    queue_number: null,
    request_date: "2024-11-03T09:52:18.000Z",
    request_status: "Completed Pickup",
    service_name: "Wash",
    service_type_id: 1,
  },
  {
    id: 9,
    store_id: 1,
    user_id: 4,
    customer_id: 3,
    tracking_code: "#5ABF9472FDC0F23F4A648",
    customer_fullname: "Maria Clara Santos",
    customer_type: "Walk-In",
    delivery_date: null,
    notes: "Fragile items, handle with care.",
    payment_method: "Credit Card",
    pickup_date: null,
    queue_number: 15,
    request_date: "2024-11-02T11:30:00.000Z",
    request_status: "In Progress",
    service_name: "Dry Clean",
    service_type_id: 2,
  },
  {
    id: 10,
    store_id: 1,
    user_id: 5,
    customer_id: 4,
    tracking_code: "#7C14BC458C292E8C83A90",
    customer_fullname: "Carlos Magno",
    customer_type: "Online",
    delivery_date: "2024-11-05T09:00:00.000Z",
    notes: null,
    payment_method: "Cash on Delivery",
    pickup_date: "2024-11-01T14:00:00.000Z",
    queue_number: null,
    request_date: "2024-11-01T09:00:00.000Z",
    request_status: "Scheduled for Pickup",
    service_name: "Wash & Fold",
    service_type_id: 1,
  },
  {
    id: 11,
    store_id: 1,
    user_id: 6,
    customer_id: 5,
    tracking_code: "#DAF4E63F2B8233B69A7A2",
    customer_fullname: "Lia Martinez",
    customer_type: "Walk-In",
    delivery_date: null,
    notes: "Special request for fabric softener.",
    payment_method: "Debit Card",
    pickup_date: null,
    queue_number: 20,
    request_date: "2024-11-03T08:15:00.000Z",
    request_status: "Pending",
    service_name: "Wash",
    service_type_id: 1,
  },
  {
    id: 12,
    store_id: 1,
    user_id: 7,
    customer_id: 6,
    tracking_code: "#B0C82F71F555E8E3C7F60",
    customer_fullname: "Rafael Cortez",
    customer_type: "Online",
    delivery_date: null,
    notes: "Urgent service needed.",
    payment_method: "PayPal",
    pickup_date: "2024-11-02T10:00:00.000Z",
    queue_number: null,
    request_date: "2024-11-02T09:45:00.000Z",
    request_status: "Completed Pickup",
    service_name: "Express Wash",
    service_type_id: 3,
  },
];
